version: "3.5"

services:
  ws1:
    container_name: ws1
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - ws-network

  ws2:
    container_name: ws2
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3001:3000
    networks:
      - ws-network

  pubsub:
    image: redis
    ports:
      - 6379:6379
    networks:
      - ws-network


networks:
    ws-network:
      driver: bridge